#!/usr/bin/env python3
# Copyright (C) 2019 - 2025, Kyoril. All rights reserved.
"""Dump the narrative content already in the game (quests, characters, quest items, zones) as
Markdown, located by zone and atlas place, as source material for docs/world/bible.md.

    python tools/world/extract_canon.py --map 0 --out generated/world/canon_map_0.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from worldkit.cli_query import open_map
from worldkit.report import quest_givers
from worldkit.spawns import unit_spawn_records


def _where(query, x: float, z: float) -> str:
    pois = query.atlas.pois_at(x, z) if query.atlas else []
    area = query.area_at(x, z)
    zone = query.zone_names.get(area) if area else None
    parts = [n for n in (zone, pois[0]["name"] if pois else None) if n]
    return " / ".join(parts) + f" ({x:.0f}, {z:.0f})" if parts else f"({x:.0f}, {z:.0f})"


def _text(value: str) -> str:
    return " ".join((value or "").split())


def build_canon_markdown(data, map_entry, query) -> str:
    lines = [f"# In-game canon: map {map_entry.id} ({map_entry.name})", "",
             "Generated by tools/world/extract_canon.py. Source material for the bible, not the bible.", ""]
    givers = quest_givers(data, map_entry)
    giver_names: dict[int, list[str]] = {}
    ender_names: dict[int, list[str]] = {}
    for unit in data.units.values():
        for quest_id in unit.quests:
            giver_names.setdefault(quest_id, []).append(unit.name)
        for quest_id in unit.end_quests:
            ender_names.setdefault(quest_id, []).append(unit.name)
    for obj in data.objects.values():
        for quest_id in obj.quests:
            giver_names.setdefault(quest_id, []).append(f"{obj.name} (object)")
        for quest_id in obj.end_quests:
            ender_names.setdefault(quest_id, []).append(f"{obj.name} (object)")

    lines += ["## Quests", ""]
    for quest_id in sorted(data.quests):
        quest = data.quests[quest_id]
        where = _where(query, *givers[quest_id][0]) if quest_id in givers else "not given on this map"
        lines.append(f"### {quest_id}. {quest.name} (level {quest.questlevel})")
        lines.append(f"- Giver: {', '.join(giver_names.get(quest_id, ['-']))} - {where}")
        lines.append(f"- Turn in: {', '.join(ender_names.get(quest_id, ['-']))}")
        if quest.prevquestid or quest.nextquestid:
            lines.append(f"- Chain: prev {quest.prevquestid or '-'}, next {quest.nextquestid or '-'}")
        for label, value in (("Details", quest.detailstext), ("Objectives", quest.objectivestext),
                             ("Request", quest.requestitemstext), ("Reward text", quest.offerrewardtext)):
            if value:
                lines.append(f"- {label}: {_text(value)}")
        lines.append("")

    lines += ["## Characters", "", "| Unit | Name | Subname | Level | Where | Gives | Ends |", "|---|---|---|---|---|---|---|"]
    spawns_by_unit: dict[int, list] = {}
    for record in unit_spawn_records(map_entry):
        spawns_by_unit.setdefault(record.entry, []).append(record)
    for unit_id in sorted(data.units):
        unit = data.units[unit_id]
        records = spawns_by_unit.get(unit_id, [])
        where = _where(query, records[0].x, records[0].z) if records else "not spawned on this map"
        if len(records) > 1:
            where += f" (+{len(records) - 1} more)"
        lines.append(f"| {unit_id} | {unit.name} | {unit.subname} | {unit.minlevel}-{unit.maxlevel} | {where} | "
                     f"{', '.join(map(str, unit.quests)) or '-'} | {', '.join(map(str, unit.end_quests)) or '-'} |")

    lines += ["", "## Quest items", ""]
    quest_items = sorted({r.itemid for q in data.quests.values() for r in q.requirements if r.itemid})
    for item_id in quest_items:
        item = data.items.get(item_id)
        description = f" - {_text(item.description)}" if item is not None and item.description else ""
        lines.append(f"- {item_id}: {item.name if item is not None else '?'}{description}")

    lines += ["", "## Zones", ""]
    for zone_id in sorted(data.zones):
        zone = data.zones[zone_id]
        parent = data.zones[zone.parentzone].name if zone.parentzone in data.zones else "-"
        lines.append(f"- {zone_id}: {zone.name} (parent: {parent})")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--map", type=int, default=0)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    data, map_entry, query = open_map(args.map)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_canon_markdown(data, map_entry, query), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
