# Copyright (C) 2019 - 2025, Kyoril. All rights reserved.
"""
Guards the link between the two warrior sound tables that nothing else connects.

``tools/sfx_gen/recipes/warrior.py`` (``SOUNDS``) is what gets generated and written to
``data/client/Sound/Spells/Warrior/``. ``tools/warrior_visuals/author_sounds.py``
(``ENTRIES``) is what turns those files into playable sound catalog entries. Nothing checks
that the two agree, so renaming a sound in one table and not the other produces a catalog
entry pointing at a file that was never generated -- and that is only caught after the data
has already been written.
"""

import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

sys.path.insert(0, os.path.join(ROOT, "tools", "sfx_gen"))
from recipes import warrior as sfx_warrior  # noqa: E402

sys.path.insert(0, os.path.join(ROOT, "tools", "warrior_visuals"))
import author_sounds  # noqa: E402


def _entry_sound_names():
    """The sound names (filenames minus ``.wav``) referenced across every catalog entry."""
    names = []
    for _entry_id, _name, files, *_rest in author_sounds.ENTRIES:
        for f in files:
            base = os.path.basename(f)
            assert base.endswith(".wav"), f"unexpected non-wav file in ENTRIES: {f}"
            names.append(base[: -len(".wav")])
    return names


class WarriorSoundCatalogConsistencyTests(unittest.TestCase):
    def test_every_generated_sound_is_referenced_by_a_catalog_entry(self):
        entry_names = set(_entry_sound_names())
        missing = sorted(set(sfx_warrior.SOUNDS) - entry_names)
        self.assertEqual(missing, [],
                         f"sounds generated by warrior.SOUNDS but not referenced by any "
                         f"author_sounds.ENTRIES entry: {missing}")

    def test_every_catalog_entry_file_is_a_generated_sound(self):
        entry_names = _entry_sound_names()
        unknown = sorted(set(entry_names) - set(sfx_warrior.SOUNDS))
        self.assertEqual(unknown, [],
                         f"author_sounds.ENTRIES references sound names that "
                         f"warrior.SOUNDS does not generate: {unknown}")

    def test_no_catalog_entry_references_the_same_sound_name_twice(self):
        names = _entry_sound_names()
        seen = set()
        duplicates = sorted({n for n in names if n in seen or seen.add(n)})
        self.assertEqual(duplicates, [],
                         f"sound name(s) referenced by more than one ENTRIES file list: "
                         f"{duplicates}")


if __name__ == "__main__":
    unittest.main()
