CREATE DATABASE IF NOT EXISTS `mmo_login`;
CREATE DATABASE IF NOT EXISTS `mmo_realm`;
CREATE DATABASE IF NOT EXISTS `mmo_world`;

GRANT ALL PRIVILEGES ON *.* TO 'root' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `mmo_login`.* TO 'mmo';
GRANT ALL PRIVILEGES ON `mmo_realm`.* TO 'mmo';
GRANT ALL PRIVILEGES ON `mmo_world`.* TO 'mmo';
