name: Linux Servers

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
    - uses: actions/checkout@v1
    - name: configure
      run: sudo apt-get install libmysqlclient-dev && git submodule update --init && mkdir build && cd build && cmake ../ 
    - name: make
      run: cd build && make
    - name: unit tests
      run: cd bin && ./unit_tests
