name: Linux Servers

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:        
    - uses: actions/checkout@v1
    
    - name: configure
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get install gcc-11 g++-11 libmysqlclient-dev uuid-dev && git submodule update --init
      
    - name: cmake
      run:   mkdir build && cd build && cmake ../
      shell: bash
      env:
        CC:   gcc-11
        CXX:  g++-11
        
    - name: make
      run: cd build && make
      
    - name: unit tests
      run: cd bin && ./unit_tests
      
